server:
  port: 9090

spring:
  profiles:
    active: dev

  datasource:
    max-poolsize: 10
    connect-timeout-ms: 3000
    validate-timeout-ms: 3000



---
spring:
  profiles: dev
  datasource:
    zj:
      test1:
        url: jdbc:mysql://localhost:3306/sqltest?useSSL=false
        username: root
        password: backpack4224889
  mongodb:
    url: mongodb://name:pass@localhost:27017/zjtest
   #redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:




logging:
  path: F:\IDEA\ZJTest1
  file: ZJLog.log



